// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6f_AuH-HZj4UqSFkk0Gn9gJbNmd4Gfg',
    appId: '1:612573295924:web:77719731d20bf69a4d6161',
    messagingSenderId: '612573295924',
    projectId: 'fasum-app-8fcb7',
    authDomain: 'fasum-app-8fcb7.firebaseapp.com',
    databaseURL: 'https://fasum-app-8fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-8fcb7.firebasestorage.app',
    measurementId: 'G-E1F7GPLG7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMwt3bydj0dYyAaYEFc0vAqf9s5vMmX1c',
    appId: '1:612573295924:android:013b9c073bc139c44d6161',
    messagingSenderId: '612573295924',
    projectId: 'fasum-app-8fcb7',
    databaseURL: 'https://fasum-app-8fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-8fcb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6vFGF1t0xKM2DyaapyOZqcb777nqDIA',
    appId: '1:612573295924:ios:ce57745b332edae94d6161',
    messagingSenderId: '612573295924',
    projectId: 'fasum-app-8fcb7',
    databaseURL: 'https://fasum-app-8fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-8fcb7.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP6vFGF1t0xKM2DyaapyOZqcb777nqDIA',
    appId: '1:612573295924:ios:ce57745b332edae94d6161',
    messagingSenderId: '612573295924',
    projectId: 'fasum-app-8fcb7',
    databaseURL: 'https://fasum-app-8fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-8fcb7.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy6f_AuH-HZj4UqSFkk0Gn9gJbNmd4Gfg',
    appId: '1:612573295924:web:3a518f8ca2353d664d6161',
    messagingSenderId: '612573295924',
    projectId: 'fasum-app-8fcb7',
    authDomain: 'fasum-app-8fcb7.firebaseapp.com',
    databaseURL: 'https://fasum-app-8fcb7-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-8fcb7.firebasestorage.app',
    measurementId: 'G-T9QSWHEX0R',
  );
}
