// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2eDx1oH9K6462TAtfwlkskTeWkwMkPGw',
    appId: '1:477158646767:web:efc2894965d6048c010c1a',
    messagingSenderId: '477158646767',
    projectId: 'eddo-app',
    authDomain: 'eddo-app.firebaseapp.com',
    databaseURL: 'https://eddo-app-default-rtdb.firebaseio.com',
    storageBucket: 'eddo-app.firebasestorage.app',
    measurementId: 'G-P5Q6LYPVLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7jiCNWEqPGwa7q8uEtiuMDjhZOU_nncg',
    appId: '1:477158646767:android:080eeaedc95ac8c2010c1a',
    messagingSenderId: '477158646767',
    projectId: 'eddo-app',
    databaseURL: 'https://eddo-app-default-rtdb.firebaseio.com',
    storageBucket: 'eddo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDD6pCweoFaOTa6JUMDSR55-IpY0fz7s',
    appId: '1:477158646767:ios:5a5b36787c95ba7e010c1a',
    messagingSenderId: '477158646767',
    projectId: 'eddo-app',
    databaseURL: 'https://eddo-app-default-rtdb.firebaseio.com',
    storageBucket: 'eddo-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDD6pCweoFaOTa6JUMDSR55-IpY0fz7s',
    appId: '1:477158646767:ios:5a5b36787c95ba7e010c1a',
    messagingSenderId: '477158646767',
    projectId: 'eddo-app',
    databaseURL: 'https://eddo-app-default-rtdb.firebaseio.com',
    storageBucket: 'eddo-app.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2eDx1oH9K6462TAtfwlkskTeWkwMkPGw',
    appId: '1:477158646767:web:916eb642f32b6ddf010c1a',
    messagingSenderId: '477158646767',
    projectId: 'eddo-app',
    authDomain: 'eddo-app.firebaseapp.com',
    databaseURL: 'https://eddo-app-default-rtdb.firebaseio.com',
    storageBucket: 'eddo-app.firebasestorage.app',
    measurementId: 'G-30GL7JBCQY',
  );

}